### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by MauMaxxa** [TheGipsyDanger/react-native-template-vindicce-expo#2]
When you use plop to generate a new flow, inside views/ElementNavigator/Layout/index.js you have to correct line 4 and add one more '../':

`import { External } from '../../../../components'`

**Comment by TheGipsyDanger** [comment]
Thanks for finding this error.
I made a small change that should solve this problem.

Em ter., 11 de ago. de 2020 às 17:17, Mauro Callegari <
notifications@github.com> escreveu:

**Comment by TheGipsyDanger** [comment]
Thanks for finding this error.
I made a small change that should solve this problem.
